apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kiali-server
    releaseName: kiali-server
    version: 2.23.0
    repo: https://kiali.org/helm-charts
    namespace: istio-system
    valuesFile: values.yaml
