apiVersion: v1
kind: Service
metadata:
  name: kraken-config
  labels:
    app: kraken-config
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: kraken-config
  type: ClusterIP
