apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml

secretGenerator:
  - name: shared-db-secret
    options:
      disableNameSuffixHash: true
    literals:
      - username=appuser
      - password=apppassword

