apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - port: 80
    targetPort: 8093
    protocol: TCP
    name: http
  - port: 8093
    targetPort: 8093
    protocol: TCP
    name: http-alt
  selector:
    app: backend
  type: ClusterIP
