apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend-test
data:
  krakend.json: |
    {
      "version": 3,
      "timeout": "3s",
      "cache_ttl": "3600s",
      "rate_limit": {
        "max_rate": 100,
        "client_max_rate": 10
      },
      "endpoints": [
        {
          "endpoint": "/health",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/health",
              "host": ["http://ws-server.krakend-test.svc.cluster.local:8080"],
              "timeout": "3s"
            }
          ]
        },
        {
          "endpoint": "/ws",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/ws",
              "host": ["http://ws-server.krakend-test.svc.cluster.local:8080"],
              "timeout": "3s"
            }
          ]
        }
      ]
    }
