apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend-test
data:
  krakend.json: |
    {
      "version": 3,
      "timeout": "5s",
      "cache_ttl": "3600s",
      "rate_limit": {
        "max_rate": 100,
        "client_max_rate": 10
      },
      "extra_config": {
        "qos/ratelimit/router": {
          "max_rate": 100,
          "client_max_rate": 10
        },
        "qos/ratelimit/proxy": {
          "max_rate": 200,
          "client_max_rate": 20
        }
      },
      "endpoints": [
        {
          "endpoint": "/socket/health",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/health",
              "host": ["http://ws-server.krakend-test.svc.cluster.local:8080"],
              "timeout": "5s"
            }
          ]
        },
        {
          "endpoint": "/socket/status",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/",
              "host": ["http://ws-server.krakend-test.svc.cluster.local:8080"],
              "timeout": "5s"
            }
          ]
        },
        {
          "endpoint": "/socket/ws",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/ws",
              "host": ["http://ws-server.krakend-test.svc.cluster.local:8080"],
              "timeout": "5s"
            }
          ]
        }
      ]
    }
