apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: krakend-gateway
  namespace: krakend-test
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: krakend-vs
  namespace: krakend-test
spec:
  hosts:
  - "*"
  gateways:
  - krakend-gateway
  http:
  # All /socket/* endpoints via KrakenD (including WebSocket support)
  - match:
    - uri:
        prefix: /socket
    route:
    - destination:
        host: krakend
        port:
          number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http2
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
