apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend
data:
  krakend.json: |
    {
      "version": 3,
      "port": 8080,
      "timeout": "10000ms",
      "cache_ttl": "300s",
      "name": "My API Gateway",
      "endpoints": [
        {
          "endpoint": "/api/auth/register",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/api/auth/register",
              "host": [
                "http://backend.backend"
              ]
            }
          ]
        },
        {
          "endpoint": "/frontend",
          "method": "GET",
          "output_encoding": "no-op",
          "backend": [
            {
              "url_pattern": "/",
              "encoding": "no-op",
              "host": [
                "http://frontend.frontend"
              ]
            }
          ]
        }
      ]
    }
