apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: krakend
  namespace: krakend
spec:
  gateways:
    - mesh
  hosts:
    - krakend
  http:
      route:
      - destination:
          host: krakend-svc
          port:
            number: 80
