apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-ingressgateway
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: internal
  nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: internal
  rules:
    - http:
        paths:
          - path: /grafana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana.monitoring
                port:
                  number: 80
    - http:
        paths:
          - path: /argocd(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: argocd-server.argocd
                port:
                  number: 80
