apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 1
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 500Mi
  bootstrap:
    initdb:
      database: appuser
      owner: appuser
      secret:
        name: shared-db-secret
