apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-infra-v127
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/niteeshchaudhary/k8_istio_krakend.git'
    targetRevision: HEAD
    path: k8s/overlays/dev/infra/istio-v127
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cluster-infra
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].failurePolicy
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].failurePolicy
        - .webhooks[].clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
