apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.2
    helm:
      values: |
        controller:
          watchIngressWithoutClass: false
          ingressClass: nginx

          ingressClassResource:
            name: internal
            enabled: true
            default: false
            controllerValue: k8s.io/internal-ingress-nginx
          publishService:
            enabled: true
          publishService:
            enabled: true
          service:
            type: NodePort
            nodePorts:
              http: 32482
              https: 31361
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx