apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-internal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.2
    helm:
      values: |
        controller:
          watchIngressWithoutClass: false
          ingressClass: internal

          ingressClassResource:
            name: internal
            enabled: true
            default: false
            controllerValue: k8s.io/internal-ingress-nginx
            
          publishService:
            enabled: true
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30442
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: internal-ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: v1
kind: Namespace
metadata:
  name: internal-ingress-nginx

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: internal
spec:
  controller: k8s.io/internal-ingress-nginx