apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/infra/keycloak
  - ../../../../base/infra/keycloak/database.yaml

secretGenerator:
  - name: shared-db-secret
    namespace: keycloak
    options:
      disableNameSuffixHash: true
    literals:
      - username=appuser
      - password=apppassword
