apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: frontend
        image: niteesh20/myapp-frontend:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /usr/share/nginx/html${VITE_ROUTE_PREFIX}
          cp -rn /usr/share/nginx/html/* /usr/share/nginx/html${VITE_ROUTE_PREFIX} || true
          nginx -g 'daemon off;'
        ports:
        - containerPort: 80 # Assuming port 80 for frontend
        env:
        - name: VITE_ROUTE_PREFIX
          value: /127/frontend/
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

