apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: frontend
        image: niteesh20/myapp-frontend:ad17cd212a76706c92731e554acad4d2a0fe52a9
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /usr/share/nginx/html${VITE_ROUTE_PREFIX}
          cp -rn /usr/share/nginx/html/* /usr/share/nginx/html${VITE_ROUTE_PREFIX} || true
          sed -i "s|%%VITE_ROUTE_PREFIX%%|${VITE_ROUTE_PREFIX}|g" /usr/share/nginx/html${VITE_ROUTE_PREFIX}/index.html
          sed -i "s|%%VITE_API_BASE_URL%%|${VITE_API_BASE_URL}|g" /usr/share/nginx/html${VITE_ROUTE_PREFIX}/index.html
          sed -i "s|%%VITE_WS_URL%%|${VITE_WS_URL}|g" /usr/share/nginx/html${VITE_ROUTE_PREFIX}/index.html
          find /usr/share/nginx/html${VITE_ROUTE_PREFIX} -type f \( -name "*.html" -o -name "*.js" \) -exec sed -i "s|/assets/|${VITE_ROUTE_PREFIX}assets/|g" {} +
          sed -i "s|/index.html|${VITE_ROUTE_PREFIX}index.html|g" /etc/nginx/conf.d/default.conf
          nginx -g 'daemon off;'


        ports:
        - containerPort: 80 # Assuming port 80 for frontend
        env:
        - name: VITE_ROUTE_PREFIX
          value: /127/frontend/
        - name: VITE_API_BASE_URL
          value: http://localhost/125/api
        - name: VITE_WS_URL
          value: http://localhost/125/ws
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

