apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  gateways:
    - cluster-infra/main-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /frontend
      rewrite:
        uri: /
      route:
        - destination:
            host: frontend.frontend.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /assets
      route:
        - destination:
            host: frontend.frontend.svc.cluster.local
            port:
              number: 80
