---
# Minimal values for Istiod
revision: "1-27-0"
global:
  istioNamespace: cluster-infra
meshConfig:
  accessLogFile: /dev/stdout
  discoverySelectors:
    - matchLabels:
        istio.io/rev: 1-27-0
pilot:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
