apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/istio.yaml
  - infra/istio-gateway.yaml
  - infra/nginx-ingress.yaml
  - infra/krakend.yaml
  - infra/cnpg.yaml
  - apps/backend.yaml
  - apps/frontend.yaml
  - apps/kraken-config.yaml
  - apps/postgres.yaml

