apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/istio.yaml
  - infra/istio-v127.yaml
  - infra/istio-gateway.yaml
  - infra/istio-gateway-v127.yaml
  - infra/nginx-ingress.yaml
  - infra/krakend.yaml
  - infra/kiali-infra.yaml
  - infra/cnpg.yaml
  - infra/monitoring.yaml
  - apps/backend.yaml
  - apps/frontend.yaml
  - apps/kraken-config.yaml
  - apps/postgres.yaml
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-server-exec-rbac.yaml

