---
# Minimal values for Istiod
revision: "1-25-0"
meshConfig:
  accessLogFile: /dev/stdout
  discoverySelectors:
    - matchLabels:
        istio.io/rev: 1-25-0
pilot:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
